### ISSUE TITLE
Add support of Solhint linter

### ISSUE THREAD

**Issue by idrabenia** [CodeChain-io/solidity-language-server#21]
Hi guys!

Solium works slow and does not cover all style guide rules. 

We develop linter that allow to verify style guide, security and best practices issues! There is Solhint - https://github.com/protofire/solhint

I believe it will be very helpful for your project!

**Comment by kseo** [comment]
@idrabenia Thanks! I will take a look at solhint.

**Comment by kseo** [comment]
Landed in 377a9a7f505d24ff72475646d7d4a80023eb44d7

solidity-language-server now supports both Solium and Solhint.

**Comment by idrabenia** [comment]
Hi @kseo ,

It's great news! Your extension is awesome!

Thank you!
\- Ilya
